"public/ChatGPT Image May 1, 2025, 05_41_42 PM.png":"data:image/png;base64,",
"public/Hall-full.png":"data:image/png;base64,",
"public/arch-foreground-columbus.png":"data:image/png;base64,",
"public/arch-foreground-origins-2.png":"data:image/png;base64,",
"public/arch-foreground-origins.png":"data:image/png;base64,",
"public/arch-foreground.png":"data:image/png;base64,",
"public/arch-frontmidground.png":"data:image/png;base64,",
"public/arch-midground.png":"data:image/png;base64,",
"public/artifact-wall.png":"data:image/png;base64,",
"public/artifact-wall2.png":"data:image/png;base64,",
"public/artifact.png":"data:image/png;base64,",
"public/duality.png":"data:image/png;base64,",
"public/entropy.png":"data:image/png;base64,",
"public/hand-frame.png":"data:image/png;base64,",
"public/origins.png":"data:image/png;base64,",
